### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by levinsonmm** [levinsonmm/MI-449-SS17-741-css-intro-iMnt09#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://levinsonmm.github.io/MI-449-SS17-741-css-intro-iMnt09/) and meets the following criteria:

- [x] The website looks (nearly) identical to [this mockup](http://i.imgur.com/eabkxO7.png) in the Chrome web browser -- colors must be exact, spacing/sizes should be within about `5px` (Tips: Use the _Page Ruler_ extension to measure exact sizes/spacing; make sure you are zoomed in on the image so the white boxes are 500px wide; you might need to open the image in a new tab)
- [x] Your project is built off [this base HTML and CSS](https://gist.github.com/chrisvfritz/279c36ab6e2301e8a35526be028d8a32) (you may modify both pages however you want, e.g. adding classes or more elements)
- [x] Any CSS selectors or properties may be used, though the project is possible using only what you saw in the lesson
- [x] No spacing HTML (e.g. `<br>`, `&amp;nbsp;`) is added to `index.html`
- [x] Add at least one link (`a` element) to the page and style them to be `purple` normally, but turn `orange` on hover

**Comment by KatieMFritz** [comment]
Hi Madeline! This is a great start. ✨ 👍 

Just from eyeballing it, it looks like there is more space around and between some of your elements than in the mockup. Particularly at the top of each section (including the header), the bottom of the header, and between the images. The [Page Ruler Chrome extension](https://chrome.google.com/webstore/detail/page-ruler/jlpkojjdgbllmedoapgfodplfhcbnbpn/related?hl=en) will probably be helpful for fixing that. 🙂

Your grids of images also don't line up on the left edge with the section headings - they're a little further to the right. There should be an imaginary line straight down the left edge of everything inside those sections.

Let me know if you get stuck on any of this! I'm available on Slack off and on during Friday, Saturday, and Monday. 😸

**Comment by levinsonmm** [comment]
Hey! I just took care of these issues I think. The problem before is that i was using the ruler on the mockup but not on my own work. This time I used live-server to make sure everything was ok. Let me know if theres anything else I should fix! :)

**Comment by KatieMFritz** [comment]
It looks much better! Nice job. 🌴 🍕 😸 

:shipit:
